### ISSUE TITLE
Docs not deployed since v0.11.4

### ISSUE THREAD

**Issue by briochemc** [JuliaApproximation/ApproxFun.jl#716]
Not sure what's wrong but the latest docs don't seem to be deployed for me. This or the ReadMe's URLs to the docs are broken.

**Comment by dlfivefifty** [comment]
I don't know what you mean: the links from the README work for me

**Comment by briochemc** [comment]
I mean if I click on the "stable" badge, I see this:

<img width="794" alt="Screen Shot 2020-09-12 at 2 06 46 am" src="https://user-images.githubusercontent.com/4486578/92948411-ac3d5e80-f49c-11ea-999f-c5f45d693776.png">

which is v0.11.4 and not the latest v0.12.2 so it missed a couple releases...

**Comment by dlfivefifty** [comment]
Hmm it's not finding BandedMatrices.jl 

I tried adding a Project.toml but that didn't fix the issue....probably I should switch to a Github workflow but I couldn't find another project that did this so not sure

**Comment by MikaelSlevinsky** [comment]
I think it's because your `travis.yml` is calling your `travis.sh` which doesn't add BandedMatrices

**Comment by briochemc** [comment]
Maybe you can add something like
```yaml
 jobs:
   include:
     - stage: Documentation
       julia: 1.5
       os: linux
       script:
         - julia --project=docs -e 'using Pkg; Pkg.instantiate()'
         - julia --project=docs --color=yes docs/make.jl
       after_success: skip
```
to your travis.yml file instead of using that travis.sh file. 

If you are looking for a GitHub-action-deployed-docs package example, I have done that for [AIBECS.jl](https://github.com/JuliaOcean/AIBECS.jl), with [that docs.yml file](https://github.com/JuliaOcean/AIBECS.jl/blob/master/.github/workflows/docs.yml):

```yaml
name: Documentation
on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:
jobs:
  docs:
    name: Documentation
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - run: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(; path=pwd()));
          Pkg.instantiate();'
      - run: julia --project=docs/ --code-coverage=user docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
and you'll have to set the secrets for this to work.
